#!/usr/bin/env python3
"""
Apply the C1 rebrand to a connector.mdx file.

Three transforms, in order:

1. Brand color:       #65DE23  ->  #c937ae  (global, safe everywhere)
2. GitHub org URL:    github.com/ConductorOne/  ->  github.com/conductorone/
                      (lowercases the org name in GitHub links, matching the docs site)
3. Brand name:        ConductorOne  ->  C1  in prose, comments, and placeholder text
                      Preserves ConductorOne when it's a URL path component
                      (e.g. dist.conductorone.com/ConductorOne/baton-* is left alone).

What is intentionally NOT changed:
  - dist.conductorone.com/ConductorOne/...  (case-sensitive distro site path)
  - conductorone.com  (product domain, already lowercase)
  - conductor.one     (tenant URL format, already lowercase)
  - support@conductorone.com  (email, already lowercase)
  - ~/.conductorone/  (file paths generated by tools, already lowercase)
  - BATON_CLIENT_ID, BATON_CLIENT_SECRET, etc.  (env var names, no ConductorOne in them)

Usage:
  python3 rebrand-connector.py <file>

Exits 0 whether or not changes were made. Prints "No changes." if the file
was already up to date.
"""

import re
import sys


def transform(content: str) -> str:
    # 1. Brand color — purely mechanical, safe inside any context.
    content = content.replace("#65DE23", "#c937ae")

    # 2. GitHub org URL — lowercase the org name in GitHub links only.
    #    This matches what was done manually in the docs site (PR 176).
    content = content.replace(
        "github.com/ConductorOne/",
        "github.com/conductorone/",
    )

    # 3. Brand name — replace ConductorOne -> C1 everywhere EXCEPT when it
    #    is a URL path component (preceded by '/').
    #
    #    The negative lookbehind (?<!/) checks the character immediately before
    #    the word boundary: if it's '/', this is a URL path segment like
    #    dist.conductorone.com/ConductorOne/baton-* and we leave it alone.
    #    All other occurrences — prose, YAML comments, angle-bracket placeholders,
    #    bold/italic markers, etc. — are replaced.
    content = re.sub(r"(?<!/)\bConductorOne\b", "C1", content)

    return content


def main() -> None:
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <file>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    with open(path, "r", encoding="utf-8") as fh:
        original = fh.read()

    updated = transform(original)

    if updated == original:
        print("No changes.")
        return

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(updated)

    changed = sum(
        1 for a, b in zip(original.splitlines(), updated.splitlines()) if a != b
    )
    print(f"Done. {changed} line(s) changed.")


if __name__ == "__main__":
    main()
